#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_from_bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_from_top = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_to_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_to_top = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010022
			public const int ptrAdapterViewBackground = 2130772002;
			
			// aapt resource value: 0x7f01000c
			public const int ptrAnimationStyle = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int ptrDrawable = 2130771974;
			
			// aapt resource value: 0x7f010024
			public const int ptrDrawableBottom = 2130772004;
			
			// aapt resource value: 0x7f010008
			public const int ptrDrawableEnd = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ptrDrawableStart = 2130771975;
			
			// aapt resource value: 0x7f010023
			public const int ptrDrawableTop = 2130772003;
			
			// aapt resource value: 0x7f010013
			public const int ptrFriction = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int ptrGoogleProgressStyle = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int ptrGoogleViewStyle = 2130771982;
			
			// aapt resource value: 0x7f010001
			public const int ptrHeaderBackground = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int ptrHeaderSubTextColor = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int ptrHeaderTextAppearance = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int ptrHeaderTextColor = 2130771970;
			
			// aapt resource value: 0x7f01001e
			public const int ptrHideRefeshableViewWhileRefreshingDuration = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int ptrHideRefeshableViewWhileRefreshingEnabled = 2130771995;
			
			// aapt resource value: 0x7f01000d
			public const int ptrIndicatorStyle = 2130771981;
			
			// aapt resource value: 0x7f010017
			public const int ptrListViewExtrasEnabled = 2130771991;
			
			// aapt resource value: 0x7f010004
			public const int ptrMode = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int ptrOverScroll = 2130771977;
			
			// aapt resource value: 0x7f010010
			public const int ptrPullLabel = 2130771984;
			
			// aapt resource value: 0x7f010021
			public const int ptrRefeshableViewProgressBarOnCenterHeight = 2130772001;
			
			// aapt resource value: 0x7f010020
			public const int ptrRefeshableViewProgressBarOnCenterWidth = 2130772000;
			
			// aapt resource value: 0x7f010011
			public const int ptrRefreshLabel = 2130771985;
			
			// aapt resource value: 0x7f010000
			public const int ptrRefreshableViewBackground = 2130771968;
			
			// aapt resource value: 0x7f010012
			public const int ptrReleaseLabel = 2130771986;
			
			// aapt resource value: 0x7f010018
			public const int ptrRotateDrawableWhilePulling = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int ptrScrollingWhileRefreshingEnabled = 2130771990;
			
			// aapt resource value: 0x7f010019
			public const int ptrSetGoogleViewLayoutSizeToActionbarHeight = 2130771993;
			
			// aapt resource value: 0x7f01001d
			public const int ptrShowGoogleStyleViewAnimationDuration = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int ptrShowGoogleStyleViewAnimationEnabled = 2130771994;
			
			// aapt resource value: 0x7f010005
			public const int ptrShowIndicator = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int ptrSmoothScrollDuration = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int ptrSmoothScrollLongDuration = 2130771989;
			
			// aapt resource value: 0x7f01000b
			public const int ptrSubHeaderTextAppearance = 2130771979;
			
			// aapt resource value: 0x7f01001f
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 2130771999;
			
			// aapt resource value: 0x7f01001c
			public const int ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 2130771996;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080003
			public const int header_footer_left_right_padding = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int header_footer_top_bottom_padding = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int header_pull_to_refresh_image_padding = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int indicator_corner_radius = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int indicator_internal_padding = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int indicator_right_padding = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int default_ptr_flip = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_ptr_rotate = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int indicator_arrow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int indicator_bg_bottom = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int indicator_bg_top = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int progress_bg_holo_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int progress_horizontal_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int progress_horizontal_holo_light_right = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int progress_indeterminate_horizontal_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int progress_primary_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int progress_secondary_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int progressbar_indeterminate_holo1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progressbar_indeterminate_holo2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int progressbar_indeterminate_holo3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int progressbar_indeterminate_holo4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int progressbar_indeterminate_holo5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int progressbar_indeterminate_holo6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int progressbar_indeterminate_holo7 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int progressbar_indeterminate_holo8 = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int bmapView = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int both = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int disabled = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int fl_inner = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int fl_inner_for_google_style = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int google = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int gridview = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int manualOnly = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int pullDownFromTop = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int pullFromEnd = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int pullFromStart = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int pullUpFromBottom = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int pull_refresh_list = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int pull_to_refresh_image = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int pull_to_refresh_progress = 2131165202;
			
			// aapt resource value: 0x7f07000f
			public const int pull_to_refresh_sub_text = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int pull_to_refresh_text = 2131165198;
			
			// aapt resource value: 0x7f070015
			public const int pulling_left_progressbar = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int pulling_progress = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int pulling_right_progressbar = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int refreshing_progress = 2131165204;
			
			// aapt resource value: 0x7f07000a
			public const int scrollview = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int webview = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout_listview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout_map = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int pull_to_refresh_header_google_style = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pull_to_refresh_header_horizontal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int pull_to_refresh_header_vertical = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int pull_to_refresh_progress_google_style = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int pulling_progress_layout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int pull_event = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int refreshing_sound = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int reset_sound = 2131099650;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090006
			public const int ApplicationName = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int pull_to_refresh_from_bottom_pull_label = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int pull_to_refresh_from_bottom_refreshing_label = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int pull_to_refresh_from_bottom_release_label = 2131296260;
			
			// aapt resource value: 0x7f090000
			public const int pull_to_refresh_pull_label = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int pull_to_refresh_refreshing_label = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int pull_to_refresh_release_label = 2131296257;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int Mono_Android_Theme_Splash = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int pulltorefresh = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PullToRefresh = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 34
			public const int PullToRefresh_ptrAdapterViewBackground = 34;
			
			// aapt resource value: 12
			public const int PullToRefresh_ptrAnimationStyle = 12;
			
			// aapt resource value: 6
			public const int PullToRefresh_ptrDrawable = 6;
			
			// aapt resource value: 36
			public const int PullToRefresh_ptrDrawableBottom = 36;
			
			// aapt resource value: 8
			public const int PullToRefresh_ptrDrawableEnd = 8;
			
			// aapt resource value: 7
			public const int PullToRefresh_ptrDrawableStart = 7;
			
			// aapt resource value: 35
			public const int PullToRefresh_ptrDrawableTop = 35;
			
			// aapt resource value: 19
			public const int PullToRefresh_ptrFriction = 19;
			
			// aapt resource value: 15
			public const int PullToRefresh_ptrGoogleProgressStyle = 15;
			
			// aapt resource value: 14
			public const int PullToRefresh_ptrGoogleViewStyle = 14;
			
			// aapt resource value: 1
			public const int PullToRefresh_ptrHeaderBackground = 1;
			
			// aapt resource value: 3
			public const int PullToRefresh_ptrHeaderSubTextColor = 3;
			
			// aapt resource value: 10
			public const int PullToRefresh_ptrHeaderTextAppearance = 10;
			
			// aapt resource value: 2
			public const int PullToRefresh_ptrHeaderTextColor = 2;
			
			// aapt resource value: 30
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingDuration = 30;
			
			// aapt resource value: 27
			public const int PullToRefresh_ptrHideRefeshableViewWhileRefreshingEnabled = 27;
			
			// aapt resource value: 13
			public const int PullToRefresh_ptrIndicatorStyle = 13;
			
			// aapt resource value: 23
			public const int PullToRefresh_ptrListViewExtrasEnabled = 23;
			
			// aapt resource value: 4
			public const int PullToRefresh_ptrMode = 4;
			
			// aapt resource value: 9
			public const int PullToRefresh_ptrOverScroll = 9;
			
			// aapt resource value: 16
			public const int PullToRefresh_ptrPullLabel = 16;
			
			// aapt resource value: 33
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterHeight = 33;
			
			// aapt resource value: 32
			public const int PullToRefresh_ptrRefeshableViewProgressBarOnCenterWidth = 32;
			
			// aapt resource value: 17
			public const int PullToRefresh_ptrRefreshLabel = 17;
			
			// aapt resource value: 0
			public const int PullToRefresh_ptrRefreshableViewBackground = 0;
			
			// aapt resource value: 18
			public const int PullToRefresh_ptrReleaseLabel = 18;
			
			// aapt resource value: 24
			public const int PullToRefresh_ptrRotateDrawableWhilePulling = 24;
			
			// aapt resource value: 22
			public const int PullToRefresh_ptrScrollingWhileRefreshingEnabled = 22;
			
			// aapt resource value: 25
			public const int PullToRefresh_ptrSetGoogleViewLayoutSizeToActionbarHeight = 25;
			
			// aapt resource value: 29
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationDuration = 29;
			
			// aapt resource value: 26
			public const int PullToRefresh_ptrShowGoogleStyleViewAnimationEnabled = 26;
			
			// aapt resource value: 5
			public const int PullToRefresh_ptrShowIndicator = 5;
			
			// aapt resource value: 20
			public const int PullToRefresh_ptrSmoothScrollDuration = 20;
			
			// aapt resource value: 21
			public const int PullToRefresh_ptrSmoothScrollLongDuration = 21;
			
			// aapt resource value: 11
			public const int PullToRefresh_ptrSubHeaderTextAppearance = 11;
			
			// aapt resource value: 31
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingDuration = 31;
			
			// aapt resource value: 28
			public const int PullToRefresh_ptrViewRefeshableViewProgressBarOnCenterWhileRefreshingEnabled = 28;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
