#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TextViewCountDownDemo.Resource", IsApplication=true)]

namespace TextViewCountDownDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBackground = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int AutFormLineColor = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int BetHpoSourceBlue = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int BetHpoSourceGreen = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int BetHpoSourcePink = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int BetHpoSourceWhite = 2131034132;
			
			// aapt resource value: 0x7f050003
			public const int BorderColor = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int ButtonBetPink_Select = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int ButtonGray = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int ButtonGray_pressed = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int ButtonPink = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int ButtonPink_pressed = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int FormHeaderTextColor = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int FormLineColor = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int HintColor = 2131034114;
			
			// aapt resource value: 0x7f05001d
			public const int LiveGreen = 2131034141;
			
			// aapt resource value: 0x7f050019
			public const int LiveIcon = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int LiveIcon_pressed = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int LiveYellow = 2131034142;
			
			// aapt resource value: 0x7f05001a
			public const int MainButtonBg = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int MainButtonBg_pressed = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int MainIconBg_pressed = 2131034140;
			
			// aapt resource value: 0x7f050010
			public const int MemAccountTextColor = 2131034128;
			
			// aapt resource value: 0x7f05000c
			public const int MsgBorder1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int MsgBorder2 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int MsgContentTextColor = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int MsgTitleTextColor = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int OrderDefaultColor = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int OrderRedColor = 2131034129;
			
			// aapt resource value: 0x7f05001f
			public const int SplashColor = 2131034143;
			
			// aapt resource value: 0x7f050013
			public const int TicketBackgroundColor = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int TitleBarColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f06000c
			public const int authFormHeight = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int authFormWidth = 2131099659;
			
			// aapt resource value: 0x7f060019
			public const int betHpoMatchWidth = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int font18px = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int font20px = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int font22px = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int font24px = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int font28px = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int font30px = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int font32px = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int font34px = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int font36px = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int formHeight = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int formWidth = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int loginCheckBoxPadding = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int loginDelAndDrownDownIcon = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int loginDeleteIconPaddingR = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int loginPaddingLeft = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int loginTextSize = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int memFormContentPaddingL = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int memFormHigth = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int memFormPadding = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int memFormWidth = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int memIconMoreR = 2131099670;
			
			// aapt resource value: 0x7f06001c
			public const int orderLineSpace = 2131099676;
			
			// aapt resource value: 0x7f06001e
			public const int orderMatchHeight = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int orderMatchLeftPadding = 2131099679;
			
			// aapt resource value: 0x7f06001d
			public const int orderMatchWidth = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int orderTopHeight = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int orderWidth = 2131099674;
			
			// aapt resource value: 0x7f060023
			public const int passwordMHeight = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int passwordMLPadding = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int passwordMPadding = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int passwordMRPadding = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int passwordMWidth = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int radioPadding = 2131099681;
			
			// aapt resource value: 0x7f060017
			public const int rechageFormHeight = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int rechageFormPadding = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int ticketTitleHeight = 2131099680;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int formBorder10pxRect = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int formBorder5px = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int btnGetVarCode = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int btnSmsCode = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int button1 = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int txtMsgCode = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int AppBackgroundTheme = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int AppBackgroundThemeNoTitle = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AppBackgroundThemeNoTitleSplash = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int AutEditBoxStyle = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int AutFormEditBox = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int AutFormHeader = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int FormHeader = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int LoginButton = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int LoginEditBoxStyle = 2130968581;
			
			// aapt resource value: 0x7f040010
			public const int Mono_Android_Theme_Splash = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int RegDoneInfoText = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int RegEditBoxStyle = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int RegInputLiner = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int RegLine = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int ShowPwdButton = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int TitleBar = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int dialog = 2130968580;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
