#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TitleBarDemo.Resource", IsApplication=true)]

namespace TitleBarDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int ShowText = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int AppBackground = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int MainButtonBg = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int MainButtonBg_pressed = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int TitleBarColor = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000c
			public const int authFormHeight = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int authFormWidth = 2131034123;
			
			// aapt resource value: 0x7f050019
			public const int betHpoMatchWidth = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int font18px = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int font20px = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int font22px = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int font24px = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int font28px = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int font30px = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int font32px = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int font34px = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int font36px = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int formHeight = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int formWidth = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int loginCheckBoxPadding = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int loginDelAndDrownDownIcon = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int loginDeleteIconPaddingR = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int loginPaddingLeft = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int loginTextSize = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int memFormContentPaddingL = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int memFormHigth = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int memFormPadding = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int memFormWidth = 2131034130;
			
			// aapt resource value: 0x7f050016
			public const int memIconMoreR = 2131034134;
			
			// aapt resource value: 0x7f05001c
			public const int orderLineSpace = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int orderMatchHeight = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int orderMatchLeftPadding = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int orderMatchWidth = 2131034141;
			
			// aapt resource value: 0x7f05001b
			public const int orderTopHeight = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int orderWidth = 2131034138;
			
			// aapt resource value: 0x7f050021
			public const int radioPadding = 2131034145;
			
			// aapt resource value: 0x7f050017
			public const int rechageFormHeight = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int rechageFormPadding = 2131034136;
			
			// aapt resource value: 0x7f050020
			public const int ticketTitleHeight = 2131034144;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int titleicon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnTitleRightButton = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int ibtnBack = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int lblTitle = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int linLeft = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int linRight = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] TakePicture = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int TakePicture_ShowText = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
