#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlideMenuFragment.Resource", IsApplication=true)]

namespace SlideMenuFragment
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_to_right = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_normal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int banner_unit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bannian = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int booklist_bg_unit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int booklist_item_bg_unit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int booklist_menu_about = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int booklist_menu_bg_unit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int booklist_menu_bg_unit2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int booklist_menu_help = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int booklist_menu_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int booklist_menu_std = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int booklist_menu_synchronize = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int booklist_menu_user = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_launcher = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int lib_mini_book = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int lib_title_bg_unit = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int line_read_option = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int lxqg = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int monoandroidsplash = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int oper_title = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int oper_title2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int p1 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int p2 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int p3 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int p4 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int p5 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int p6 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int p7 = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int MyButton = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int action_settings = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int center_frame = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int iv_left = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int iv_right = 2131230727;
			
			// aapt resource value: 0x7f080014
			public const int iv_user_left = 2131230740;
			
			// aapt resource value: 0x7f080005
			public const int left_frame = 2131230725;
			
			// aapt resource value: 0x7f08000a
			public const int list_contect = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int list_image = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int list_title = 2131230728;
			
			// aapt resource value: 0x7f08000e
			public const int llr_business_management = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int llr_energy_management = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int llr_financial_management = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int llr_hr_management = 2131230733;
			
			// aapt resource value: 0x7f080012
			public const int llr_project_management = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int llr_purchasing_management = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int llr_supply_management = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int mainPage = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int mlist = 2131230722;
			
			// aapt resource value: 0x7f080013
			public const int right_frame = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int slidingMenu = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int userLayout = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int center_frame = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int details = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int left_fragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int left_frame = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int right_fragment = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int right_frame = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int user = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int action_settings = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int test = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int title1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int title2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int title3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int title4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int title5 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int title6 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int title7 = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Mono_Android_Theme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
